name: License Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for licenses
        uses: Steffen911/license-checker-action@0.1.0
