name: License Scan (Python)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pip-licenses
          pip install -r requirements.txt || true
          pip install poetry && poetry install || true
      - name: Generate license report
        run: |
          pip-licenses --format=markdown --output-file=THIRD_PARTY_LICENSES.md
      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: third-party-licenses
          path: THIRD_PARTY_LICENSES.md
