name: Require Linked Issue

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-linked-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
